### ISSUE TITLE
failed to compile for go 1.6 for 386

### ISSUE THREAD

**Issue by vtolstov** [cloudflare/golibs#7]
github.com/cloudflare/golibs/bytepool/bytepool.go:28: constant 4294967295 overflows int
github.com/cloudflare/golibs/bytepool/bytepool.go:29: constant 4294967295 overflows int

**Comment by majek** [comment]
fancy submitting a PR?

**Comment by mbijon** [comment]
@vtolstov The value 4294967295 should be the max, valid 32-bit unsigned integer. I'm not able to reproduce this on Amazon Linux running the 32-bit golang version.

What CPU platform & OS did you geenrate this error on?

**Comment by vtolstov** [comment]
i'm cross compile under go 1.6 from amd64 to i386

**Comment by vtolstov** [comment]
for me this works, check pr #8

**Comment by spance** [comment]
You just need change `MaxUint32` to `MaxInt32` for 32bit platform at [bytepool.go#L28](https://github.com/cloudflare/golibs/blob/master/bytepool/bytepool.go#L28) and L29 .

**Comment by mbijon** [comment]
@spance, that change will prevent an error, but it also halves the cached byte slice size. That may or may not change people's expectations from this bytepool lib.

Note that the MaxUint32 in Go is 2^32-1, or 4294967295. That's true on *both* 64-bit and 32-bit OSes and *most* 32/64-bit CPUs:
* Set here: https://golang.org/src/math/const.go
(and since @vtolstov is compiling from source, I supect it's on a non-386 or non-amd64 CPU. Which WOULD mean that a number lower than 4294967295 could be the limit here)

@vtolstov that's why I'm asking what platform & OS you're on. It may be that there's a platform-specific limit to work around here, instead of changing the interface or pool-size in ways that break other users' expectations of golibs/bytepool

**Comment by mbijon** [comment]
@vtolstov To get better info about this, could you run Go's internal math tests?
* https://golang.org/src/math/all_test.go

It's possible Go's test coverage misses a larger problem in golang on your OS/CPU >> I worry that none of those tests above implement a range with MaxUint32, even though it's set in math/const.go.

**Comment by spance** [comment]
@mbijon Consider `maxSizeLog := log2Ceil(maxSize)`, note that the `maxSizeLog ∈ [0, 32]`.
If `maxSizeLog==32`, then `tp.maxSize = (1 << maxSizeLog) - 1` will be overflow on 32bit platform.
As I said, check `tp.maxSize <= 0` is necessary on 32bit platform.

**Comment by mbijon** [comment]
@spance Maybe I'm missing something by not having a 32-bit CPU. But since log2(4294967295) == 32, I'm able to get these tests to pass as-is on a 64-bit CPU running the 32-bit 386 golang package (not self-compiled). That's why I'm stuck on getting more info about the environment where a failure occurs for @vtolstov.

Regardless, you're solution of `tp.maxSize <= 0` DOES work ... I just want to avoid changing the cache size of this helper if it's avoidable on systems that allow specifying an unsigned 32-bit int vs a signed 31-bit int.

**Comment by l2dy** [comment]
maxSize is an int field. As the spec says, `int is a signed integer type that is at least 32 bits in size.`
So maxSize may overflow when assigned a value larger than math.MaxInt32, hence the compile error.

**Comment by mbijon** [comment]
@l2dy, MaxUInt == 4294967295 & is a 32-bit integer => (2^32)-1. Unsigned integers trade a bit of ± for a bit of + numeric range ...still 32-bits

**Comment by l2dy** [comment]
@mbijon, a 32 bit int (maxSize) can only hold up to 2^31 - 1.
```
package main

import (
	"fmt"
	"math"
)

func main() {
	var i int32
	i = math.MaxUint32
	fmt.Println(i)
}
```

**Comment by mbijon** [comment]
gah, good catch @l2dy, I'm being obtuse ... this: 4294967295, does fit in 32-bits, BUT I got hung up on the uint32 and didn't equate it to an int32 *type* like you're talking about. You're right, 2147483647 is the max there.

Which also means I was obtuse in only looking at the `Init(drainPeriod time.Duration, maxSize uint32)` def on [line 25](https://github.com/cloudflare/golibs/blob/master/bytepool/bytepool.go#L25). The problem with 64 vs 32 bit systems is in the type def on [line 19](https://github.com/cloudflare/golibs/blob/master/bytepool/bytepool.go#L19): `maxSize int`.

And there's the *real problem*: The whole BytePool package *except* L19 uses uint32's. So the fix from @spance in [this comment](https://github.com/cloudflare/golibs/issues/7#issuecomment-194734714) is part of the solution, but probably not enough to make this bulletproof on 32-bit  OS+CPU systems.

To support 32-bit systems 100%, BytePool needs to be more specific (`maxSize int32` on L19) and stop using uint32 & use int32 for maxSize _everywhere_
(...or, BytePool needs to make a potentially breaking public change & implement `maxSize uint32` on L19)

**Comment by mbijon** [comment]
...or not. Realized we can still support uint32 items in the pool by limiting maxSize instead of tp.maxSize.

Tks @spance for the 32-bit MaxInt32 catch.

@vtolstov, above PR should get you running.

**Comment by l2dy** [comment]
@mbijon, this if statement is useless as `uint32 is the set of all unsigned 32-bit integers. Range: 0 through 4294967295.`, why keeping it?
```
	if maxSize > math.MaxUint32 {
		maxSize = math.MaxUint32
	}
```

**Comment by spance** [comment]
On any platform, it's always true `maxSize(uint32) <= math.MaxUint32`.
So the "if" statement would be useless. https://github.com/cloudflare/golibs/commit/2c19c292a845a093571cb9ac17add7a186eeddbf#diff-a1f899023910ea8cb8eb76091456943cR26

**Comment by vtolstov** [comment]
Thanks for help!
